#!/bin/bash
#
# "$1" is doc/readme.txt
# "$2" is output file

DIR="$(cd "$(dirname "$0")" && pwd)"

source "$DIR"/wiki-common

noedit_header > "$2"

cat <<EOF >> "$2"
==Team Lead==

EOF

sed -ne 'H;$x;$s%^\n%%;$s%\n   *% %g;$p' \
    -ne '%== Developers ==%,%== Supporters ==%p' \
    "$1" > "$2"

sed 's%.*Eihrul.*%&\n\n== Team Members ==\n\n%'

sed '%== Developers ==%d'
