#!/bin/bash
#
# "$1..n-1" is input files
# "$n" is output file

DIR="$(cd "$(dirname "$0")" && pwd)"
source "$DIR"/wiki-common

for i
do
    if [ -n "$INFILES" ]
    then
        INFILES="$INFILES $OUTFILE"
    else
        INFILES="$OUTFILE"
    fi
    OUTFILE="$i"
done

noedit_header > "$OUTFILE"
table_header >> "$OUTFILE"

sed -n '/|-/,/|}/p' $INFILES | sed '/|}/d' >> "$OUTFILE"

table_end >> "$OUTFILE"
