#!/bin/bash
#
# "$1" is usage.cfg
# "$2" is output file

DIR="$(cd "$(dirname "$0")" && pwd)"
SRC_DIR="$DIR/.."

source "$DIR"/wiki-common
source "$DIR"/generate-wiki-aliases
source "$DIR"/generate-wiki-commands
for i in "$DIR"/generate-wiki-*-vars
do
    source "$i"
done

noedit_header > "$2"
table_header >> "$2"
table_content_aliases "$1" >> "$2"
table_content_commands "$1" >> "$2"
table_content_engine-vars "$1" >> "$2"
table_content_game-vars "$1" >> "$2"
table_content_weapon-vars "$1" >> "$2"
table_end >> "$2"
