#!/bin/bash
#
# "$1" is doc/readme.txt
# "$2" is output file

DIR="$(cd "$(dirname "$0")" && pwd)"

source "$DIR"/wiki-common

noedit_header > "$2"

cat <<EOF >> "$2"
== Red Eclipse Team ==

=== Team Lead ===

{| border="1" cellpadding="10" cellspacing="0"
EOF

# convert to UTF-8 and grab everything from dev tag and onward
iconv -f ISO-8859-1 -t UTF8 "$1" | sed -n '/== Developers ==/,$p;/^$/d' >> "$2"

# join lines starting with two or more spaces
sed -ne 'H;$x;$s%^\n%%;$s%\n   *% %g;$p' -i "$2"

# tables and members tag after eihrul
sed 's%.*Eihrul.*%&\n|}\n\n=== Team Members ===\n\n{| border="1" cellpadding="10" cellspacing="0"%' -i "$2"

# delete dev tag
sed '/== Developers ==/d' -i "$2"

# table end and start around supporters tag
sed 's%.*== Supporters ==.*%|}\n\n&\n%' -i "$2"

# tablification of devs
sed 's%^\* \([^-]*\) - \([^-]*\) - \(.*\)%| \1\n| \2\n| \3\n|-%' -i "$2"
