#!/bin/bash
#
# "$1" is usage.cfg
# "$2" is output file

DIR="$(cd "$(dirname "$0")" && pwd)"
CFG_FILES="$DIR/../../data/*.cfg"

source "$DIR"/wiki-common

table_content_aliases ()
{
    IFS=$'\n'
    for i in $(grep "^setdesc" "$1" | sort)
    do
        ALI="$(echo $i | sed -n 's%^setdesc "\([^"]*\)".*%\1%p')"

        CFG_DEF="$(grep -hr "^$ALI *=.*" $CFG_FILES)"
        if [ -z "$CFG_DEF" ]; then continue; fi

        DESC="$(echo $i | sed -e 's%^setdesc "[^"]*" "\(.*\)" "[^"]*"%\1%' -e 's%\^%%g')"
        PARAM="$(echo $i | sed 's%^setdesc "[^"]*" ".*" "\([^"]*\)"%\1%')"
        PARAM="$(echo $PARAM | sed 's% %\&nbsp;%g')"

        TYPE_STRING="alias"

        table_entry_simple "$ALI" "$PARAM" "$DESC" "$TYPE_STRING"
        done
}

noedit_header > "$2"
table_header_simple >> "$2"
table_content_aliases "$1" >> "$2"
table_end >> "$2"
