#!/bin/bash
#
# This script resaves and overwrites existing map .cfg and .mpz files by
# launching a Red Eclipse client instance and opening and saving all given maps
# A subset of map names to process may be given as arguments
# If no argument is given, processes all maps found in data/maps/

DIR="$(cd "$(dirname "$0")" && pwd)"

if [ $# -eq 0 ]
then
    MAPS="$(for map in $(ls "$DIR"/../../data/maps/*.mpz); do basename $map .mpz; done)"
else
    MAPS="$@"
fi

EDIT_MAPS="$(for map in $MAPS; do echo -n "edit $map; edittoggle 1; savemap; disconnect; "; done)"

TMPHOME="$(mktemp -d "$DIR"/tmp_home_XXXXX)"

# Make the RE window as discrete as possible
echo -e "fullscreen 0\nscr_w 640\nscr_h 480\nshaders 0" > "$TMPHOME"/init.cfg
echo -e "setinfo '"foo"' 0x000000 0\nmastervol 0\n" > "$TMPHOME"/config.cfg

"$DIR"/../../redeclipse.sh -h"$TMPHOME" -x"$EDIT_MAPS quit"

mv "$TMPHOME"/maps/*.{cfg,mpz} "$DIR"/../../data/maps

rm -r "$TMPHOME"
